spring:
  application:
    name: jpa_crud
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: sh
    password: sh
    url: jdbc:mysql://localhost:3306/jpa

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true